### ISSUE TITLE
creating stochastic model with fix number scenarios reports error. 

### ISSUE THREAD

**Issue by fqiang** [joehuchette/StochJuMP.jl#12]
julia> firststage = StochasticModel(2)
ERROR: MethodError: `StochasticModel` has no method matching StochasticModel(::Int64)
Closest candidates are:
  StochasticModel(::Any, ::Any)
  StochasticModel(::Any, ::Any, ::Any)

---------
Or how about to auto increment the number for each adding of the children stochastic block?

**Comment by fqiang** [comment]
```julia
function StochasticModel(nscen::Int)
    m = JuMP.Model(solver=JuMP.UnsetSolver())
    m.ext[:Stochastic] = StochasticData(JuMP.Model[],nothing,nscen)
    return m
end
```
adding explicit constructor works.

**Comment by joehuchette** [comment]
You need to specify this with a keyword argument:
```jl
firststage = StochasticModel(num_scenarios=2)
```
